local system = require("core.system")

local opt = vim.opt


opt.autoindent = true
opt.autoread = true
opt.autowrite = true
-- opt.backspace = "indent,eol,start"
opt.backup = false
opt.backupskip = "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim"
opt.breakat = [[\ \	;:,!?]]
opt.breakindentopt = "shift:2,min:20"
opt.clipboard = "unnamedplus"
opt.cmdheight = 1  -- 0, 1, 2
opt.cmdwinheight = 5
opt.complete = ".,w,b,k,kspell"
opt.completeopt = "menuone,noselect,popup"
opt.concealcursor = "niv"
opt.conceallevel = 0
opt.cursorcolumn = true
opt.cursorline = true
opt.diffopt = "filler,iwhite,internal,linematch:60,algorithm:patience"
opt.display = "lastline"
opt.encoding = "utf-8"
opt.equalalways = false
opt.errorbells = true
opt.expandtab = true
opt.fileformats = "unix,mac,dos"
opt.foldenable = true
opt.foldlevelstart = 99
opt.formatoptions = "1jcroql"
opt.grepformat = "%f:%l:%c:%m"
opt.grepprg = "rg --hidden --vimgrep --smart-case --"
opt.helpheight = 12
opt.hidden = true
opt.history = 2000
opt.ignorecase = true
opt.inccommand = "nosplit"
opt.incsearch = true
opt.infercase = true
opt.jumpoptions = "stack"
opt.laststatus = 3
opt.linebreak = true
opt.list = true
opt.listchars = "tab:»·,nbsp:+,trail:·,extends:→,precedes:←"
opt.magic = true
opt.mousescroll = "ver:3,hor:6"
opt.number = true
opt.previewheight = 12
-- Do NOT adjust the following option (pumblend) if you're using transparent background
opt.pumblend = 0
opt.pumheight = 15
opt.redrawtime = 1500
opt.relativenumber = true
opt.ruler = true
opt.scrolloff = 2
opt.sessionoptions = "buffers,curdir,folds,help,tabpages,winpos,winsize"
opt.shada = "!,'500,<50,@100,s10,h"
opt.shiftround = true
opt.shiftwidth = 2
opt.shortmess = "aoOTIcF"
opt.showbreak = "↳  "
opt.showcmd = true
opt.showmatch = true
opt.showmode = false
opt.showtabline = 2
opt.sidescrolloff = 5
opt.signcolumn = "yes"
opt.smartcase = true
opt.smarttab = true
opt.smoothscroll = true
opt.softtabstop = 2
opt.splitbelow = true
opt.splitkeep = "screen"
opt.splitright = true
opt.startofline = false
opt.swapfile = false
opt.switchbuf = "usetab,uselast"
opt.synmaxcol = 2500
opt.syntax = "on"
opt.tabstop = 2
opt.termguicolors = true
opt.timeout = true
opt.timeoutlen = 300
opt.ttimeout = true
opt.ttimeoutlen = 0
opt.undodir = system.cache_dir .. "/undo/"
opt.undofile = true
-- Please do NOT set `updatetime` to above 500, otherwise most plugins may not function correctly
opt.updatetime = 200
opt.viewoptions = "folds,cursor,curdir,slash,unix"
opt.virtualedit = "block"
opt.visualbell = true
opt.whichwrap = "h,l,<,>,[,],~"
opt.wildignore = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**"
opt.wildignorecase = true
-- Do NOT adjust the following option (winblend) if you're using transparent background
opt.winblend = 0
opt.winminwidth = 10
opt.winwidth = 30
opt.wrap = false
opt.wrapscan = true
opt.writebackup = false
